[package]
name = "loki_to_slack_notification"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json","blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slack-hook = "0.8"
mockito = "1.6.1"
tempfile = "3.19.0"