name: CI

on:
  push:
    tags:
      - *
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --verbose

  build:
    if: startsWith(github.ref, 'refs/tags/')  # Запускать только при создании тега
    runs-on: ubuntu-latest
    needs: test  # Зависит от успешного завершения тестов
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/avkviring/loki-to-slack-notification:latest
            ghcr.io/avkviring/loki-to-slack-notification:${{ github.ref_name }}
